name       : python3-qt4
version    : '4.12'
release    : 5
source     :
    - https://pilotfiber.dl.sourceforge.net/project/pyqt/PyQt4/PyQt-4.12/PyQt4_gpl_x11-4.12.tar.gz : 3c1d4b55314adb3e1132de8fc2a92eed216d37e58aceed41294dbca210ca88db
license    : GPL-3.0
component  : programming.python
summary    : python3-qt4 are the python3 bindings for Qt4.
description: |
    python3-qt4 are the python3 bindings for Qt4.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python-3.5)
    - pkgconfig(QtGui)
    - python3-dbus
    - python3-sip-devel
rundeps    :
    - python3-sip
    - python-qt4
setup      : |
    python3 configure-ng.py --confirm-license --no-sip-files -q /usr/bin/qmake-qt4
build      : |
    sed -i "s|/usr/bin/moc|/usr/bin/moc-qt4|g" ./*/Makefile
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/lib64
    rm -rf $installdir/usr/share
